# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DataLoadWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_Dataload(object):
    def setupUi(self, Dialog_Dataload):
        Dialog_Dataload.setObjectName("Dialog_Dataload")
        Dialog_Dataload.resize(240, 67)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/数据加载.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog_Dataload.setWindowIcon(icon)
        self.gridLayout = QtWidgets.QGridLayout(Dialog_Dataload)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(Dialog_Dataload)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.spinBox = QtWidgets.QSpinBox(Dialog_Dataload)
        self.spinBox.setMinimum(1)
        self.spinBox.setObjectName("spinBox")
        self.gridLayout.addWidget(self.spinBox, 0, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(57, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 0, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog_Dataload)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 1, 1, 1, 1)

        self.retranslateUi(Dialog_Dataload)
        self.buttonBox.accepted.connect(Dialog_Dataload.accept)
        self.buttonBox.rejected.connect(Dialog_Dataload.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog_Dataload)

    def retranslateUi(self, Dialog_Dataload):
        _translate = QtCore.QCoreApplication.translate
        Dialog_Dataload.setWindowTitle(_translate("Dialog_Dataload", "数据加载"))
        self.label.setText(_translate("Dialog_Dataload", "通道数量："))
import Ui.qrc_rc
