# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FilterWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_filter(object):
    def setupUi(self, Dialog_filter):
        Dialog_filter.setObjectName("Dialog_filter")
        Dialog_filter.resize(182, 93)
        Dialog_filter.setMaximumSize(QtCore.QSize(182, 93))
        self.gridLayout = QtWidgets.QGridLayout(Dialog_filter)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(Dialog_filter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.comboBox_filter = QtWidgets.QComboBox(Dialog_filter)
        self.comboBox_filter.setObjectName("comboBox_filter")
        self.comboBox_filter.addItem("")
        self.gridLayout.addWidget(self.comboBox_filter, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(Dialog_filter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.spinBox_freq = QtWidgets.QSpinBox(Dialog_filter)
        self.spinBox_freq.setProperty("value", 1)
        self.spinBox_freq.setObjectName("spinBox_freq")
        self.gridLayout.addWidget(self.spinBox_freq, 1, 1, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog_filter)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 2, 0, 1, 2)

        self.retranslateUi(Dialog_filter)
        self.buttonBox.accepted.connect(Dialog_filter.accept)
        self.buttonBox.rejected.connect(Dialog_filter.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog_filter)

    def retranslateUi(self, Dialog_filter):
        _translate = QtCore.QCoreApplication.translate
        Dialog_filter.setWindowTitle(_translate("Dialog_filter", "滤波窗口"))
        self.label.setText(_translate("Dialog_filter", "滤波选择："))
        self.comboBox_filter.setItemText(0, _translate("Dialog_filter", "巴特沃斯高通"))
        self.label_2.setText(_translate("Dialog_filter", "频率选择"))
