# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1092, 848)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/数据分析.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(0, 1, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget_tab = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget_tab.setObjectName("tabWidget_tab")
        self.gridLayout.addWidget(self.tabWidget_tab, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1092, 23))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_dataload = QtWidgets.QAction(MainWindow)
        self.action_dataload.setObjectName("action_dataload")
        self.action_filter = QtWidgets.QAction(MainWindow)
        self.action_filter.setObjectName("action_filter")
        self.action_time = QtWidgets.QAction(MainWindow)
        self.action_time.setObjectName("action_time")
        self.action_waterfall = QtWidgets.QAction(MainWindow)
        self.action_waterfall.setObjectName("action_waterfall")
        self.action_stft = QtWidgets.QAction(MainWindow)
        self.action_stft.setObjectName("action_stft")
        self.action_export = QtWidgets.QAction(MainWindow)
        self.action_export.setObjectName("action_export")
        self.action_coding = QtWidgets.QAction(MainWindow)
        self.action_coding.setObjectName("action_coding")
        self.menu.addAction(self.action_dataload)
        self.menu.addAction(self.action_filter)
        self.menu.addAction(self.action_coding)
        self.menu_2.addAction(self.action_waterfall)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())

        self.retranslateUi(MainWindow)
        self.action_dataload.triggered.connect(MainWindow.HandlerLoad)
        self.action_filter.triggered.connect(MainWindow.HandlerFilter)
        self.action_waterfall.triggered.connect(MainWindow.HandlerWaterFall)
        self.action_coding.triggered.connect(MainWindow.HandlerCoding)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "数据分析工具"))
        self.menu.setTitle(_translate("MainWindow", "数据处理"))
        self.menu_2.setTitle(_translate("MainWindow", "绘图控制"))
        self.action_dataload.setText(_translate("MainWindow", "数据加载"))
        self.action_filter.setText(_translate("MainWindow", "数据滤波"))
        self.action_time.setText(_translate("MainWindow", "多通道时域图"))
        self.action_waterfall.setText(_translate("MainWindow", "瀑布图"))
        self.action_stft.setText(_translate("MainWindow", "短时傅里叶"))
        self.action_export.setText(_translate("MainWindow", "数据导出"))
        self.action_coding.setText(_translate("MainWindow", "高速编码"))
import Ui.qrc_rc
