# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TimeSettingWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_time_setting(object):
    def setupUi(self, Dialog_time_setting):
        Dialog_time_setting.setObjectName("Dialog_time_setting")
        Dialog_time_setting.resize(247, 315)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog_time_setting)
        self.verticalLayout.setObjectName("verticalLayout")
        self.comboBox_channel = QtWidgets.QComboBox(Dialog_time_setting)
        self.comboBox_channel.setObjectName("comboBox_channel")
        self.verticalLayout.addWidget(self.comboBox_channel)
        self.stackedWidget_Item = QtWidgets.QStackedWidget(Dialog_time_setting)
        self.stackedWidget_Item.setObjectName("stackedWidget_Item")
        self.verticalLayout.addWidget(self.stackedWidget_Item)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog_time_setting)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Dialog_time_setting)
        self.stackedWidget_Item.setCurrentIndex(-1)
        self.buttonBox.accepted.connect(Dialog_time_setting.accept)
        self.buttonBox.rejected.connect(Dialog_time_setting.reject)
        self.comboBox_channel.currentIndexChanged['int'].connect(self.stackedWidget_Item.setCurrentIndex)
        QtCore.QMetaObject.connectSlotsByName(Dialog_time_setting)

    def retranslateUi(self, Dialog_time_setting):
        _translate = QtCore.QCoreApplication.translate
        Dialog_time_setting.setWindowTitle(_translate("Dialog_time_setting", "绘图选项"))
